/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AddressesRouteImport } from './routes/addresses'
import { Route as BlockedRouteImport } from './routes/blocked'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AccountEditRouteImport } from './routes/account.edit'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAdminsRouteImport } from './routes/admin.admins'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminMerchantApplicationsRouteImport } from './routes/admin.merchant-applications'
import { Route as AdminMerchantsRouteImport } from './routes/admin.merchants'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminRiderApplicationsRouteImport } from './routes/admin.rider-applications'
import { Route as AdminRidersRouteImport } from './routes/admin.riders'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminZonesRouteImport } from './routes/admin.zones'
import { Route as MerchantIndexRouteImport } from './routes/merchant.index'
import { Route as MerchantApplyRouteImport } from './routes/merchant.apply'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as RiderIndexRouteImport } from './routes/rider.index'
import { Route as RiderAccountRouteImport } from './routes/rider.account'
import { Route as RiderApplyRouteImport } from './routes/rider.apply'
import { Route as RiderPerformanceRouteImport } from './routes/rider.performance'
import { Route as RiderSupportRouteImport } from './routes/rider.support'
import { Route as RiderWalletRouteImport } from './routes/rider.wallet'
import { Route as StoreMerchantIdRouteImport } from './routes/store.$merchantId'
import { Route as MerchantApplyFormRouteImport } from './routes/merchant.apply.form'
import { Route as MerchantApplySubmittedRouteImport } from './routes/merchant.apply.submitted'
import { Route as RiderApplyFormRouteImport } from './routes/rider.apply.form'
import { Route as RiderApplySubmittedRouteImport } from './routes/rider.apply.submitted'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressesRoute = AddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockedRoute = BlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountEditRoute = AccountEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AccountRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admin/admins',
  path: '/admin/admins',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMerchantApplicationsRoute =
  AdminMerchantApplicationsRouteImport.update({
    id: '/admin/merchant-applications',
    path: '/admin/merchant-applications',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminMerchantsRoute = AdminMerchantsRouteImport.update({
  id: '/admin/merchants',
  path: '/admin/merchants',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRiderApplicationsRoute = AdminRiderApplicationsRouteImport.update({
  id: '/admin/rider-applications',
  path: '/admin/rider-applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRidersRoute = AdminRidersRouteImport.update({
  id: '/admin/riders',
  path: '/admin/riders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/admin/support',
  path: '/admin/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminZonesRoute = AdminZonesRouteImport.update({
  id: '/admin/zones',
  path: '/admin/zones',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantIndexRoute = MerchantIndexRouteImport.update({
  id: '/merchant/',
  path: '/merchant/',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantApplyRoute = MerchantApplyRouteImport.update({
  id: '/merchant/apply',
  path: '/merchant/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderIndexRoute = RiderIndexRouteImport.update({
  id: '/rider/',
  path: '/rider/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderAccountRoute = RiderAccountRouteImport.update({
  id: '/rider/account',
  path: '/rider/account',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderApplyRoute = RiderApplyRouteImport.update({
  id: '/rider/apply',
  path: '/rider/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderPerformanceRoute = RiderPerformanceRouteImport.update({
  id: '/rider/performance',
  path: '/rider/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderSupportRoute = RiderSupportRouteImport.update({
  id: '/rider/support',
  path: '/rider/support',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderWalletRoute = RiderWalletRouteImport.update({
  id: '/rider/wallet',
  path: '/rider/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreMerchantIdRoute = StoreMerchantIdRouteImport.update({
  id: '/store/$merchantId',
  path: '/store/$merchantId',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantApplyFormRoute = MerchantApplyFormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => MerchantApplyRoute,
} as any)
const MerchantApplySubmittedRoute = MerchantApplySubmittedRouteImport.update({
  id: '/submitted',
  path: '/submitted',
  getParentRoute: () => MerchantApplyRoute,
} as any)
const RiderApplyFormRoute = RiderApplyFormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => RiderApplyRoute,
} as any)
const RiderApplySubmittedRoute = RiderApplySubmittedRouteImport.update({
  id: '/submitted',
  path: '/submitted',
  getParentRoute: () => RiderApplyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/addresses': typeof AddressesRoute
  '/blocked': typeof BlockedRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/account/edit': typeof AccountEditRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/merchant-applications': typeof AdminMerchantApplicationsRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/rider-applications': typeof AdminRiderApplicationsRoute
  '/admin/riders': typeof AdminRidersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/zones': typeof AdminZonesRoute
  '/merchant/apply': typeof MerchantApplyRouteWithChildren
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/rider/account': typeof RiderAccountRoute
  '/rider/apply': typeof RiderApplyRouteWithChildren
  '/rider/performance': typeof RiderPerformanceRoute
  '/rider/support': typeof RiderSupportRoute
  '/rider/wallet': typeof RiderWalletRoute
  '/store/$merchantId': typeof StoreMerchantIdRoute
  '/admin/': typeof AdminIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/rider/': typeof RiderIndexRoute
  '/merchant/apply/form': typeof MerchantApplyFormRoute
  '/merchant/apply/submitted': typeof MerchantApplySubmittedRoute
  '/rider/apply/form': typeof RiderApplyFormRoute
  '/rider/apply/submitted': typeof RiderApplySubmittedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/addresses': typeof AddressesRoute
  '/blocked': typeof BlockedRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/account/edit': typeof AccountEditRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/merchant-applications': typeof AdminMerchantApplicationsRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/rider-applications': typeof AdminRiderApplicationsRoute
  '/admin/riders': typeof AdminRidersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/zones': typeof AdminZonesRoute
  '/merchant/apply': typeof MerchantApplyRouteWithChildren
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/rider/account': typeof RiderAccountRoute
  '/rider/apply': typeof RiderApplyRouteWithChildren
  '/rider/performance': typeof RiderPerformanceRoute
  '/rider/support': typeof RiderSupportRoute
  '/rider/wallet': typeof RiderWalletRoute
  '/store/$merchantId': typeof StoreMerchantIdRoute
  '/admin': typeof AdminIndexRoute
  '/merchant': typeof MerchantIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/rider': typeof RiderIndexRoute
  '/merchant/apply/form': typeof MerchantApplyFormRoute
  '/merchant/apply/submitted': typeof MerchantApplySubmittedRoute
  '/rider/apply/form': typeof RiderApplyFormRoute
  '/rider/apply/submitted': typeof RiderApplySubmittedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/addresses': typeof AddressesRoute
  '/blocked': typeof BlockedRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/account/edit': typeof AccountEditRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/merchant-applications': typeof AdminMerchantApplicationsRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/rider-applications': typeof AdminRiderApplicationsRoute
  '/admin/riders': typeof AdminRidersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/zones': typeof AdminZonesRoute
  '/merchant/apply': typeof MerchantApplyRouteWithChildren
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/rider/account': typeof RiderAccountRoute
  '/rider/apply': typeof RiderApplyRouteWithChildren
  '/rider/performance': typeof RiderPerformanceRoute
  '/rider/support': typeof RiderSupportRoute
  '/rider/wallet': typeof RiderWalletRoute
  '/store/$merchantId': typeof StoreMerchantIdRoute
  '/admin/': typeof AdminIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/rider/': typeof RiderIndexRoute
  '/merchant/apply/form': typeof MerchantApplyFormRoute
  '/merchant/apply/submitted': typeof MerchantApplySubmittedRoute
  '/rider/apply/form': typeof RiderApplyFormRoute
  '/rider/apply/submitted': typeof RiderApplySubmittedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/addresses'
    | '/blocked'
    | '/cart'
    | '/checkout'
    | '/help'
    | '/login'
    | '/register'
    | '/settings'
    | '/account/edit'
    | '/admin/admins'
    | '/admin/analytics'
    | '/admin/audit-logs'
    | '/admin/customers'
    | '/admin/merchant-applications'
    | '/admin/merchants'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/rider-applications'
    | '/admin/riders'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/zones'
    | '/merchant/apply'
    | '/orders/$orderId'
    | '/rider/account'
    | '/rider/apply'
    | '/rider/performance'
    | '/rider/support'
    | '/rider/wallet'
    | '/store/$merchantId'
    | '/admin/'
    | '/merchant/'
    | '/orders/'
    | '/rider/'
    | '/merchant/apply/form'
    | '/merchant/apply/submitted'
    | '/rider/apply/form'
    | '/rider/apply/submitted'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/addresses'
    | '/blocked'
    | '/cart'
    | '/checkout'
    | '/help'
    | '/login'
    | '/register'
    | '/settings'
    | '/account/edit'
    | '/admin/admins'
    | '/admin/analytics'
    | '/admin/audit-logs'
    | '/admin/customers'
    | '/admin/merchant-applications'
    | '/admin/merchants'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/rider-applications'
    | '/admin/riders'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/zones'
    | '/merchant/apply'
    | '/orders/$orderId'
    | '/rider/account'
    | '/rider/apply'
    | '/rider/performance'
    | '/rider/support'
    | '/rider/wallet'
    | '/store/$merchantId'
    | '/admin'
    | '/merchant'
    | '/orders'
    | '/rider'
    | '/merchant/apply/form'
    | '/merchant/apply/submitted'
    | '/rider/apply/form'
    | '/rider/apply/submitted'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/addresses'
    | '/blocked'
    | '/cart'
    | '/checkout'
    | '/help'
    | '/login'
    | '/register'
    | '/settings'
    | '/account/edit'
    | '/admin/admins'
    | '/admin/analytics'
    | '/admin/audit-logs'
    | '/admin/customers'
    | '/admin/merchant-applications'
    | '/admin/merchants'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/rider-applications'
    | '/admin/riders'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/zones'
    | '/merchant/apply'
    | '/orders/$orderId'
    | '/rider/account'
    | '/rider/apply'
    | '/rider/performance'
    | '/rider/support'
    | '/rider/wallet'
    | '/store/$merchantId'
    | '/admin/'
    | '/merchant/'
    | '/orders/'
    | '/rider/'
    | '/merchant/apply/form'
    | '/merchant/apply/submitted'
    | '/rider/apply/form'
    | '/rider/apply/submitted'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  AddressesRoute: typeof AddressesRoute
  BlockedRoute: typeof BlockedRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminMerchantApplicationsRoute: typeof AdminMerchantApplicationsRoute
  AdminMerchantsRoute: typeof AdminMerchantsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminRiderApplicationsRoute: typeof AdminRiderApplicationsRoute
  AdminRidersRoute: typeof AdminRidersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminZonesRoute: typeof AdminZonesRoute
  MerchantApplyRoute: typeof MerchantApplyRouteWithChildren
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  RiderAccountRoute: typeof RiderAccountRoute
  RiderApplyRoute: typeof RiderApplyRouteWithChildren
  RiderPerformanceRoute: typeof RiderPerformanceRoute
  RiderSupportRoute: typeof RiderSupportRoute
  RiderWalletRoute: typeof RiderWalletRoute
  StoreMerchantIdRoute: typeof StoreMerchantIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  MerchantIndexRoute: typeof MerchantIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  RiderIndexRoute: typeof RiderIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addresses': {
      id: '/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocked': {
      id: '/blocked'
      path: '/blocked'
      fullPath: '/blocked'
      preLoaderRoute: typeof BlockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/edit': {
      id: '/account/edit'
      path: '/edit'
      fullPath: '/account/edit'
      preLoaderRoute: typeof AccountEditRouteImport
      parentRoute: typeof AccountRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admin/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/merchant-applications': {
      id: '/admin/merchant-applications'
      path: '/admin/merchant-applications'
      fullPath: '/admin/merchant-applications'
      preLoaderRoute: typeof AdminMerchantApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/merchants': {
      id: '/admin/merchants'
      path: '/admin/merchants'
      fullPath: '/admin/merchants'
      preLoaderRoute: typeof AdminMerchantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rider-applications': {
      id: '/admin/rider-applications'
      path: '/admin/rider-applications'
      fullPath: '/admin/rider-applications'
      preLoaderRoute: typeof AdminRiderApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/riders': {
      id: '/admin/riders'
      path: '/admin/riders'
      fullPath: '/admin/riders'
      preLoaderRoute: typeof AdminRidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/zones': {
      id: '/admin/zones'
      path: '/admin/zones'
      fullPath: '/admin/zones'
      preLoaderRoute: typeof AdminZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/': {
      id: '/merchant/'
      path: '/merchant'
      fullPath: '/merchant/'
      preLoaderRoute: typeof MerchantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/apply': {
      id: '/merchant/apply'
      path: '/merchant/apply'
      fullPath: '/merchant/apply'
      preLoaderRoute: typeof MerchantApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/': {
      id: '/rider/'
      path: '/rider'
      fullPath: '/rider/'
      preLoaderRoute: typeof RiderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/account': {
      id: '/rider/account'
      path: '/rider/account'
      fullPath: '/rider/account'
      preLoaderRoute: typeof RiderAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/apply': {
      id: '/rider/apply'
      path: '/rider/apply'
      fullPath: '/rider/apply'
      preLoaderRoute: typeof RiderApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/performance': {
      id: '/rider/performance'
      path: '/rider/performance'
      fullPath: '/rider/performance'
      preLoaderRoute: typeof RiderPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/support': {
      id: '/rider/support'
      path: '/rider/support'
      fullPath: '/rider/support'
      preLoaderRoute: typeof RiderSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/wallet': {
      id: '/rider/wallet'
      path: '/rider/wallet'
      fullPath: '/rider/wallet'
      preLoaderRoute: typeof RiderWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$merchantId': {
      id: '/store/$merchantId'
      path: '/store/$merchantId'
      fullPath: '/store/$merchantId'
      preLoaderRoute: typeof StoreMerchantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/apply/form': {
      id: '/merchant/apply/form'
      path: '/form'
      fullPath: '/merchant/apply/form'
      preLoaderRoute: typeof MerchantApplyFormRouteImport
      parentRoute: typeof MerchantApplyRoute
    }
    '/merchant/apply/submitted': {
      id: '/merchant/apply/submitted'
      path: '/submitted'
      fullPath: '/merchant/apply/submitted'
      preLoaderRoute: typeof MerchantApplySubmittedRouteImport
      parentRoute: typeof MerchantApplyRoute
    }
    '/rider/apply/form': {
      id: '/rider/apply/form'
      path: '/form'
      fullPath: '/rider/apply/form'
      preLoaderRoute: typeof RiderApplyFormRouteImport
      parentRoute: typeof RiderApplyRoute
    }
    '/rider/apply/submitted': {
      id: '/rider/apply/submitted'
      path: '/submitted'
      fullPath: '/rider/apply/submitted'
      preLoaderRoute: typeof RiderApplySubmittedRouteImport
      parentRoute: typeof RiderApplyRoute
    }
  }
}

interface AccountRouteChildren {
  AccountEditRoute: typeof AccountEditRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountEditRoute: AccountEditRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface MerchantApplyRouteChildren {
  MerchantApplyFormRoute: typeof MerchantApplyFormRoute
  MerchantApplySubmittedRoute: typeof MerchantApplySubmittedRoute
}

const MerchantApplyRouteChildren: MerchantApplyRouteChildren = {
  MerchantApplyFormRoute: MerchantApplyFormRoute,
  MerchantApplySubmittedRoute: MerchantApplySubmittedRoute,
}

const MerchantApplyRouteWithChildren = MerchantApplyRoute._addFileChildren(
  MerchantApplyRouteChildren,
)

interface RiderApplyRouteChildren {
  RiderApplyFormRoute: typeof RiderApplyFormRoute
  RiderApplySubmittedRoute: typeof RiderApplySubmittedRoute
}

const RiderApplyRouteChildren: RiderApplyRouteChildren = {
  RiderApplyFormRoute: RiderApplyFormRoute,
  RiderApplySubmittedRoute: RiderApplySubmittedRoute,
}

const RiderApplyRouteWithChildren = RiderApplyRoute._addFileChildren(
  RiderApplyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  AddressesRoute: AddressesRoute,
  BlockedRoute: BlockedRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  AdminAdminsRoute: AdminAdminsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminMerchantApplicationsRoute: AdminMerchantApplicationsRoute,
  AdminMerchantsRoute: AdminMerchantsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminRiderApplicationsRoute: AdminRiderApplicationsRoute,
  AdminRidersRoute: AdminRidersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminZonesRoute: AdminZonesRoute,
  MerchantApplyRoute: MerchantApplyRouteWithChildren,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  RiderAccountRoute: RiderAccountRoute,
  RiderApplyRoute: RiderApplyRouteWithChildren,
  RiderPerformanceRoute: RiderPerformanceRoute,
  RiderSupportRoute: RiderSupportRoute,
  RiderWalletRoute: RiderWalletRoute,
  StoreMerchantIdRoute: StoreMerchantIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  MerchantIndexRoute: MerchantIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  RiderIndexRoute: RiderIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
