/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlockedRouteImport } from './routes/blocked'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAdminsRouteImport } from './routes/admin/admins'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminAuditLogsRouteImport } from './routes/admin/audit-logs'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminMerchantApplicationsRouteImport } from './routes/admin/merchant-applications'
import { Route as AdminMerchantsRouteImport } from './routes/admin/merchants'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminRiderApplicationsRouteImport } from './routes/admin/rider-applications'
import { Route as AdminRidersRouteImport } from './routes/admin/riders'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSupportRouteImport } from './routes/admin/support'
import { Route as AdminZonesRouteImport } from './routes/admin/zones'
import { Route as AuthSetPasswordRouteImport } from './routes/auth.set-password'
import { Route as CustomerAccountRouteImport } from './routes/customer/account'
import { Route as CustomerAddressesRouteImport } from './routes/customer/addresses'
import { Route as CustomerCartRouteImport } from './routes/customer/cart'
import { Route as CustomerCheckoutRouteImport } from './routes/customer/checkout'
import { Route as CustomerSettingsRouteImport } from './routes/customer/settings'
import { Route as MerchantIndexRouteImport } from './routes/merchant/index'
import { Route as RiderIndexRouteImport } from './routes/rider/index'
import { Route as RiderAccountRouteImport } from './routes/rider/account'
import { Route as RiderPerformanceRouteImport } from './routes/rider/performance'
import { Route as RiderSupportRouteImport } from './routes/rider/support'
import { Route as RiderWalletRouteImport } from './routes/rider/wallet'
import { Route as StoreMerchantIdRouteImport } from './routes/store.$merchantId'
import { Route as CustomerAccountEditRouteImport } from './routes/customer/account.edit'
import { Route as CustomerOrdersIndexRouteImport } from './routes/customer/orders.index'
import { Route as CustomerOrdersOrderIdRouteImport } from './routes/customer/orders.$orderId'
import { Route as MerchantApplyIndexRouteImport } from './routes/merchant/apply/index'
import { Route as MerchantApplyFormRouteImport } from './routes/merchant/apply/form'
import { Route as MerchantApplySubmittedRouteImport } from './routes/merchant/apply/submitted'
import { Route as MerchantOrdersIndexRouteImport } from './routes/merchant/orders/index'
import { Route as MerchantProductsIndexRouteImport } from './routes/merchant/products/index'
import { Route as MerchantProfileIndexRouteImport } from './routes/merchant/profile/index'
import { Route as MerchantSettingsIndexRouteImport } from './routes/merchant/settings/index'
import { Route as MerchantStaffIndexRouteImport } from './routes/merchant/staff/index'
import { Route as RiderApplyIndexRouteImport } from './routes/rider/apply/index'
import { Route as RiderApplyFormRouteImport } from './routes/rider/apply/form'
import { Route as RiderApplySubmittedRouteImport } from './routes/rider/apply/submitted'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockedRoute = BlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admin/admins',
  path: '/admin/admins',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMerchantApplicationsRoute =
  AdminMerchantApplicationsRouteImport.update({
    id: '/admin/merchant-applications',
    path: '/admin/merchant-applications',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminMerchantsRoute = AdminMerchantsRouteImport.update({
  id: '/admin/merchants',
  path: '/admin/merchants',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRiderApplicationsRoute = AdminRiderApplicationsRouteImport.update({
  id: '/admin/rider-applications',
  path: '/admin/rider-applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRidersRoute = AdminRidersRouteImport.update({
  id: '/admin/riders',
  path: '/admin/riders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/admin/support',
  path: '/admin/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminZonesRoute = AdminZonesRouteImport.update({
  id: '/admin/zones',
  path: '/admin/zones',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSetPasswordRoute = AuthSetPasswordRouteImport.update({
  id: '/auth/set-password',
  path: '/auth/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerAccountRoute = CustomerAccountRouteImport.update({
  id: '/customer/account',
  path: '/customer/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerAddressesRoute = CustomerAddressesRouteImport.update({
  id: '/customer/addresses',
  path: '/customer/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerCartRoute = CustomerCartRouteImport.update({
  id: '/customer/cart',
  path: '/customer/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerCheckoutRoute = CustomerCheckoutRouteImport.update({
  id: '/customer/checkout',
  path: '/customer/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerSettingsRoute = CustomerSettingsRouteImport.update({
  id: '/customer/settings',
  path: '/customer/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantIndexRoute = MerchantIndexRouteImport.update({
  id: '/merchant/',
  path: '/merchant/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderIndexRoute = RiderIndexRouteImport.update({
  id: '/rider/',
  path: '/rider/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderAccountRoute = RiderAccountRouteImport.update({
  id: '/rider/account',
  path: '/rider/account',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderPerformanceRoute = RiderPerformanceRouteImport.update({
  id: '/rider/performance',
  path: '/rider/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderSupportRoute = RiderSupportRouteImport.update({
  id: '/rider/support',
  path: '/rider/support',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderWalletRoute = RiderWalletRouteImport.update({
  id: '/rider/wallet',
  path: '/rider/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreMerchantIdRoute = StoreMerchantIdRouteImport.update({
  id: '/store/$merchantId',
  path: '/store/$merchantId',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerAccountEditRoute = CustomerAccountEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => CustomerAccountRoute,
} as any)
const CustomerOrdersIndexRoute = CustomerOrdersIndexRouteImport.update({
  id: '/customer/orders/',
  path: '/customer/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerOrdersOrderIdRoute = CustomerOrdersOrderIdRouteImport.update({
  id: '/customer/orders/$orderId',
  path: '/customer/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantApplyIndexRoute = MerchantApplyIndexRouteImport.update({
  id: '/merchant/apply/',
  path: '/merchant/apply/',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantApplyFormRoute = MerchantApplyFormRouteImport.update({
  id: '/merchant/apply/form',
  path: '/merchant/apply/form',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantApplySubmittedRoute = MerchantApplySubmittedRouteImport.update({
  id: '/merchant/apply/submitted',
  path: '/merchant/apply/submitted',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantOrdersIndexRoute = MerchantOrdersIndexRouteImport.update({
  id: '/merchant/orders/',
  path: '/merchant/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantProductsIndexRoute = MerchantProductsIndexRouteImport.update({
  id: '/merchant/products/',
  path: '/merchant/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantProfileIndexRoute = MerchantProfileIndexRouteImport.update({
  id: '/merchant/profile/',
  path: '/merchant/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantSettingsIndexRoute = MerchantSettingsIndexRouteImport.update({
  id: '/merchant/settings/',
  path: '/merchant/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantStaffIndexRoute = MerchantStaffIndexRouteImport.update({
  id: '/merchant/staff/',
  path: '/merchant/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderApplyIndexRoute = RiderApplyIndexRouteImport.update({
  id: '/rider/apply/',
  path: '/rider/apply/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderApplyFormRoute = RiderApplyFormRouteImport.update({
  id: '/rider/apply/form',
  path: '/rider/apply/form',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderApplySubmittedRoute = RiderApplySubmittedRouteImport.update({
  id: '/rider/apply/submitted',
  path: '/rider/apply/submitted',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blocked': typeof BlockedRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/register': typeof RegisterRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/merchant-applications': typeof AdminMerchantApplicationsRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/rider-applications': typeof AdminRiderApplicationsRoute
  '/admin/riders': typeof AdminRidersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/zones': typeof AdminZonesRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/customer/account': typeof CustomerAccountRouteWithChildren
  '/customer/addresses': typeof CustomerAddressesRoute
  '/customer/cart': typeof CustomerCartRoute
  '/customer/checkout': typeof CustomerCheckoutRoute
  '/customer/settings': typeof CustomerSettingsRoute
  '/rider/account': typeof RiderAccountRoute
  '/rider/performance': typeof RiderPerformanceRoute
  '/rider/support': typeof RiderSupportRoute
  '/rider/wallet': typeof RiderWalletRoute
  '/store/$merchantId': typeof StoreMerchantIdRoute
  '/admin/': typeof AdminIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/rider/': typeof RiderIndexRoute
  '/customer/account/edit': typeof CustomerAccountEditRoute
  '/customer/orders/$orderId': typeof CustomerOrdersOrderIdRoute
  '/merchant/apply/form': typeof MerchantApplyFormRoute
  '/merchant/apply/submitted': typeof MerchantApplySubmittedRoute
  '/rider/apply/form': typeof RiderApplyFormRoute
  '/rider/apply/submitted': typeof RiderApplySubmittedRoute
  '/customer/orders/': typeof CustomerOrdersIndexRoute
  '/merchant/apply/': typeof MerchantApplyIndexRoute
  '/merchant/orders/': typeof MerchantOrdersIndexRoute
  '/merchant/products/': typeof MerchantProductsIndexRoute
  '/merchant/profile/': typeof MerchantProfileIndexRoute
  '/merchant/settings/': typeof MerchantSettingsIndexRoute
  '/merchant/staff/': typeof MerchantStaffIndexRoute
  '/rider/apply/': typeof RiderApplyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blocked': typeof BlockedRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/register': typeof RegisterRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/merchant-applications': typeof AdminMerchantApplicationsRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/rider-applications': typeof AdminRiderApplicationsRoute
  '/admin/riders': typeof AdminRidersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/zones': typeof AdminZonesRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/customer/account': typeof CustomerAccountRouteWithChildren
  '/customer/addresses': typeof CustomerAddressesRoute
  '/customer/cart': typeof CustomerCartRoute
  '/customer/checkout': typeof CustomerCheckoutRoute
  '/customer/settings': typeof CustomerSettingsRoute
  '/rider/account': typeof RiderAccountRoute
  '/rider/performance': typeof RiderPerformanceRoute
  '/rider/support': typeof RiderSupportRoute
  '/rider/wallet': typeof RiderWalletRoute
  '/store/$merchantId': typeof StoreMerchantIdRoute
  '/admin': typeof AdminIndexRoute
  '/merchant': typeof MerchantIndexRoute
  '/rider': typeof RiderIndexRoute
  '/customer/account/edit': typeof CustomerAccountEditRoute
  '/customer/orders/$orderId': typeof CustomerOrdersOrderIdRoute
  '/merchant/apply/form': typeof MerchantApplyFormRoute
  '/merchant/apply/submitted': typeof MerchantApplySubmittedRoute
  '/rider/apply/form': typeof RiderApplyFormRoute
  '/rider/apply/submitted': typeof RiderApplySubmittedRoute
  '/customer/orders': typeof CustomerOrdersIndexRoute
  '/merchant/apply': typeof MerchantApplyIndexRoute
  '/merchant/orders': typeof MerchantOrdersIndexRoute
  '/merchant/products': typeof MerchantProductsIndexRoute
  '/merchant/profile': typeof MerchantProfileIndexRoute
  '/merchant/settings': typeof MerchantSettingsIndexRoute
  '/merchant/staff': typeof MerchantStaffIndexRoute
  '/rider/apply': typeof RiderApplyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blocked': typeof BlockedRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/register': typeof RegisterRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/merchant-applications': typeof AdminMerchantApplicationsRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/rider-applications': typeof AdminRiderApplicationsRoute
  '/admin/riders': typeof AdminRidersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/zones': typeof AdminZonesRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/customer/account': typeof CustomerAccountRouteWithChildren
  '/customer/addresses': typeof CustomerAddressesRoute
  '/customer/cart': typeof CustomerCartRoute
  '/customer/checkout': typeof CustomerCheckoutRoute
  '/customer/settings': typeof CustomerSettingsRoute
  '/rider/account': typeof RiderAccountRoute
  '/rider/performance': typeof RiderPerformanceRoute
  '/rider/support': typeof RiderSupportRoute
  '/rider/wallet': typeof RiderWalletRoute
  '/store/$merchantId': typeof StoreMerchantIdRoute
  '/admin/': typeof AdminIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/rider/': typeof RiderIndexRoute
  '/customer/account/edit': typeof CustomerAccountEditRoute
  '/customer/orders/$orderId': typeof CustomerOrdersOrderIdRoute
  '/merchant/apply/form': typeof MerchantApplyFormRoute
  '/merchant/apply/submitted': typeof MerchantApplySubmittedRoute
  '/rider/apply/form': typeof RiderApplyFormRoute
  '/rider/apply/submitted': typeof RiderApplySubmittedRoute
  '/customer/orders/': typeof CustomerOrdersIndexRoute
  '/merchant/apply/': typeof MerchantApplyIndexRoute
  '/merchant/orders/': typeof MerchantOrdersIndexRoute
  '/merchant/products/': typeof MerchantProductsIndexRoute
  '/merchant/profile/': typeof MerchantProfileIndexRoute
  '/merchant/settings/': typeof MerchantSettingsIndexRoute
  '/merchant/staff/': typeof MerchantStaffIndexRoute
  '/rider/apply/': typeof RiderApplyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blocked'
    | '/help'
    | '/login'
    | '/partners'
    | '/register'
    | '/admin/admins'
    | '/admin/analytics'
    | '/admin/audit-logs'
    | '/admin/customers'
    | '/admin/merchant-applications'
    | '/admin/merchants'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/rider-applications'
    | '/admin/riders'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/zones'
    | '/auth/set-password'
    | '/customer/account'
    | '/customer/addresses'
    | '/customer/cart'
    | '/customer/checkout'
    | '/customer/settings'
    | '/rider/account'
    | '/rider/performance'
    | '/rider/support'
    | '/rider/wallet'
    | '/store/$merchantId'
    | '/admin/'
    | '/merchant/'
    | '/rider/'
    | '/customer/account/edit'
    | '/customer/orders/$orderId'
    | '/merchant/apply/form'
    | '/merchant/apply/submitted'
    | '/rider/apply/form'
    | '/rider/apply/submitted'
    | '/customer/orders/'
    | '/merchant/apply/'
    | '/merchant/orders/'
    | '/merchant/products/'
    | '/merchant/profile/'
    | '/merchant/settings/'
    | '/merchant/staff/'
    | '/rider/apply/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blocked'
    | '/help'
    | '/login'
    | '/partners'
    | '/register'
    | '/admin/admins'
    | '/admin/analytics'
    | '/admin/audit-logs'
    | '/admin/customers'
    | '/admin/merchant-applications'
    | '/admin/merchants'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/rider-applications'
    | '/admin/riders'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/zones'
    | '/auth/set-password'
    | '/customer/account'
    | '/customer/addresses'
    | '/customer/cart'
    | '/customer/checkout'
    | '/customer/settings'
    | '/rider/account'
    | '/rider/performance'
    | '/rider/support'
    | '/rider/wallet'
    | '/store/$merchantId'
    | '/admin'
    | '/merchant'
    | '/rider'
    | '/customer/account/edit'
    | '/customer/orders/$orderId'
    | '/merchant/apply/form'
    | '/merchant/apply/submitted'
    | '/rider/apply/form'
    | '/rider/apply/submitted'
    | '/customer/orders'
    | '/merchant/apply'
    | '/merchant/orders'
    | '/merchant/products'
    | '/merchant/profile'
    | '/merchant/settings'
    | '/merchant/staff'
    | '/rider/apply'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blocked'
    | '/help'
    | '/login'
    | '/partners'
    | '/register'
    | '/admin/admins'
    | '/admin/analytics'
    | '/admin/audit-logs'
    | '/admin/customers'
    | '/admin/merchant-applications'
    | '/admin/merchants'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/rider-applications'
    | '/admin/riders'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/zones'
    | '/auth/set-password'
    | '/customer/account'
    | '/customer/addresses'
    | '/customer/cart'
    | '/customer/checkout'
    | '/customer/settings'
    | '/rider/account'
    | '/rider/performance'
    | '/rider/support'
    | '/rider/wallet'
    | '/store/$merchantId'
    | '/admin/'
    | '/merchant/'
    | '/rider/'
    | '/customer/account/edit'
    | '/customer/orders/$orderId'
    | '/merchant/apply/form'
    | '/merchant/apply/submitted'
    | '/rider/apply/form'
    | '/rider/apply/submitted'
    | '/customer/orders/'
    | '/merchant/apply/'
    | '/merchant/orders/'
    | '/merchant/products/'
    | '/merchant/profile/'
    | '/merchant/settings/'
    | '/merchant/staff/'
    | '/rider/apply/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlockedRoute: typeof BlockedRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  PartnersRoute: typeof PartnersRoute
  RegisterRoute: typeof RegisterRoute
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminMerchantApplicationsRoute: typeof AdminMerchantApplicationsRoute
  AdminMerchantsRoute: typeof AdminMerchantsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminRiderApplicationsRoute: typeof AdminRiderApplicationsRoute
  AdminRidersRoute: typeof AdminRidersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminZonesRoute: typeof AdminZonesRoute
  AuthSetPasswordRoute: typeof AuthSetPasswordRoute
  CustomerAccountRoute: typeof CustomerAccountRouteWithChildren
  CustomerAddressesRoute: typeof CustomerAddressesRoute
  CustomerCartRoute: typeof CustomerCartRoute
  CustomerCheckoutRoute: typeof CustomerCheckoutRoute
  CustomerSettingsRoute: typeof CustomerSettingsRoute
  RiderAccountRoute: typeof RiderAccountRoute
  RiderPerformanceRoute: typeof RiderPerformanceRoute
  RiderSupportRoute: typeof RiderSupportRoute
  RiderWalletRoute: typeof RiderWalletRoute
  StoreMerchantIdRoute: typeof StoreMerchantIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  MerchantIndexRoute: typeof MerchantIndexRoute
  RiderIndexRoute: typeof RiderIndexRoute
  CustomerOrdersOrderIdRoute: typeof CustomerOrdersOrderIdRoute
  MerchantApplyFormRoute: typeof MerchantApplyFormRoute
  MerchantApplySubmittedRoute: typeof MerchantApplySubmittedRoute
  RiderApplyFormRoute: typeof RiderApplyFormRoute
  RiderApplySubmittedRoute: typeof RiderApplySubmittedRoute
  CustomerOrdersIndexRoute: typeof CustomerOrdersIndexRoute
  MerchantApplyIndexRoute: typeof MerchantApplyIndexRoute
  MerchantOrdersIndexRoute: typeof MerchantOrdersIndexRoute
  MerchantProductsIndexRoute: typeof MerchantProductsIndexRoute
  MerchantProfileIndexRoute: typeof MerchantProfileIndexRoute
  MerchantSettingsIndexRoute: typeof MerchantSettingsIndexRoute
  MerchantStaffIndexRoute: typeof MerchantStaffIndexRoute
  RiderApplyIndexRoute: typeof RiderApplyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocked': {
      id: '/blocked'
      path: '/blocked'
      fullPath: '/blocked'
      preLoaderRoute: typeof BlockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admin/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/merchant-applications': {
      id: '/admin/merchant-applications'
      path: '/admin/merchant-applications'
      fullPath: '/admin/merchant-applications'
      preLoaderRoute: typeof AdminMerchantApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/merchants': {
      id: '/admin/merchants'
      path: '/admin/merchants'
      fullPath: '/admin/merchants'
      preLoaderRoute: typeof AdminMerchantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rider-applications': {
      id: '/admin/rider-applications'
      path: '/admin/rider-applications'
      fullPath: '/admin/rider-applications'
      preLoaderRoute: typeof AdminRiderApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/riders': {
      id: '/admin/riders'
      path: '/admin/riders'
      fullPath: '/admin/riders'
      preLoaderRoute: typeof AdminRidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/zones': {
      id: '/admin/zones'
      path: '/admin/zones'
      fullPath: '/admin/zones'
      preLoaderRoute: typeof AdminZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/set-password': {
      id: '/auth/set-password'
      path: '/auth/set-password'
      fullPath: '/auth/set-password'
      preLoaderRoute: typeof AuthSetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/account': {
      id: '/customer/account'
      path: '/customer/account'
      fullPath: '/customer/account'
      preLoaderRoute: typeof CustomerAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/addresses': {
      id: '/customer/addresses'
      path: '/customer/addresses'
      fullPath: '/customer/addresses'
      preLoaderRoute: typeof CustomerAddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/cart': {
      id: '/customer/cart'
      path: '/customer/cart'
      fullPath: '/customer/cart'
      preLoaderRoute: typeof CustomerCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/checkout': {
      id: '/customer/checkout'
      path: '/customer/checkout'
      fullPath: '/customer/checkout'
      preLoaderRoute: typeof CustomerCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/settings': {
      id: '/customer/settings'
      path: '/customer/settings'
      fullPath: '/customer/settings'
      preLoaderRoute: typeof CustomerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/': {
      id: '/merchant/'
      path: '/merchant'
      fullPath: '/merchant/'
      preLoaderRoute: typeof MerchantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/': {
      id: '/rider/'
      path: '/rider'
      fullPath: '/rider/'
      preLoaderRoute: typeof RiderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/account': {
      id: '/rider/account'
      path: '/rider/account'
      fullPath: '/rider/account'
      preLoaderRoute: typeof RiderAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/performance': {
      id: '/rider/performance'
      path: '/rider/performance'
      fullPath: '/rider/performance'
      preLoaderRoute: typeof RiderPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/support': {
      id: '/rider/support'
      path: '/rider/support'
      fullPath: '/rider/support'
      preLoaderRoute: typeof RiderSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/wallet': {
      id: '/rider/wallet'
      path: '/rider/wallet'
      fullPath: '/rider/wallet'
      preLoaderRoute: typeof RiderWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$merchantId': {
      id: '/store/$merchantId'
      path: '/store/$merchantId'
      fullPath: '/store/$merchantId'
      preLoaderRoute: typeof StoreMerchantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/account/edit': {
      id: '/customer/account/edit'
      path: '/edit'
      fullPath: '/customer/account/edit'
      preLoaderRoute: typeof CustomerAccountEditRouteImport
      parentRoute: typeof CustomerAccountRoute
    }
    '/customer/orders/': {
      id: '/customer/orders/'
      path: '/customer/orders'
      fullPath: '/customer/orders/'
      preLoaderRoute: typeof CustomerOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/orders/$orderId': {
      id: '/customer/orders/$orderId'
      path: '/customer/orders/$orderId'
      fullPath: '/customer/orders/$orderId'
      preLoaderRoute: typeof CustomerOrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/apply/': {
      id: '/merchant/apply/'
      path: '/merchant/apply'
      fullPath: '/merchant/apply/'
      preLoaderRoute: typeof MerchantApplyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/apply/form': {
      id: '/merchant/apply/form'
      path: '/merchant/apply/form'
      fullPath: '/merchant/apply/form'
      preLoaderRoute: typeof MerchantApplyFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/apply/submitted': {
      id: '/merchant/apply/submitted'
      path: '/merchant/apply/submitted'
      fullPath: '/merchant/apply/submitted'
      preLoaderRoute: typeof MerchantApplySubmittedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/orders/': {
      id: '/merchant/orders/'
      path: '/merchant/orders'
      fullPath: '/merchant/orders/'
      preLoaderRoute: typeof MerchantOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/products/': {
      id: '/merchant/products/'
      path: '/merchant/products'
      fullPath: '/merchant/products/'
      preLoaderRoute: typeof MerchantProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/profile/': {
      id: '/merchant/profile/'
      path: '/merchant/profile'
      fullPath: '/merchant/profile/'
      preLoaderRoute: typeof MerchantProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/settings/': {
      id: '/merchant/settings/'
      path: '/merchant/settings'
      fullPath: '/merchant/settings/'
      preLoaderRoute: typeof MerchantSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/staff/': {
      id: '/merchant/staff/'
      path: '/merchant/staff'
      fullPath: '/merchant/staff/'
      preLoaderRoute: typeof MerchantStaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/apply/': {
      id: '/rider/apply/'
      path: '/rider/apply'
      fullPath: '/rider/apply/'
      preLoaderRoute: typeof RiderApplyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/apply/form': {
      id: '/rider/apply/form'
      path: '/rider/apply/form'
      fullPath: '/rider/apply/form'
      preLoaderRoute: typeof RiderApplyFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/apply/submitted': {
      id: '/rider/apply/submitted'
      path: '/rider/apply/submitted'
      fullPath: '/rider/apply/submitted'
      preLoaderRoute: typeof RiderApplySubmittedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CustomerAccountRouteChildren {
  CustomerAccountEditRoute: typeof CustomerAccountEditRoute
}

const CustomerAccountRouteChildren: CustomerAccountRouteChildren = {
  CustomerAccountEditRoute: CustomerAccountEditRoute,
}

const CustomerAccountRouteWithChildren = CustomerAccountRoute._addFileChildren(
  CustomerAccountRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlockedRoute: BlockedRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  PartnersRoute: PartnersRoute,
  RegisterRoute: RegisterRoute,
  AdminAdminsRoute: AdminAdminsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminMerchantApplicationsRoute: AdminMerchantApplicationsRoute,
  AdminMerchantsRoute: AdminMerchantsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminRiderApplicationsRoute: AdminRiderApplicationsRoute,
  AdminRidersRoute: AdminRidersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminZonesRoute: AdminZonesRoute,
  AuthSetPasswordRoute: AuthSetPasswordRoute,
  CustomerAccountRoute: CustomerAccountRouteWithChildren,
  CustomerAddressesRoute: CustomerAddressesRoute,
  CustomerCartRoute: CustomerCartRoute,
  CustomerCheckoutRoute: CustomerCheckoutRoute,
  CustomerSettingsRoute: CustomerSettingsRoute,
  RiderAccountRoute: RiderAccountRoute,
  RiderPerformanceRoute: RiderPerformanceRoute,
  RiderSupportRoute: RiderSupportRoute,
  RiderWalletRoute: RiderWalletRoute,
  StoreMerchantIdRoute: StoreMerchantIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  MerchantIndexRoute: MerchantIndexRoute,
  RiderIndexRoute: RiderIndexRoute,
  CustomerOrdersOrderIdRoute: CustomerOrdersOrderIdRoute,
  MerchantApplyFormRoute: MerchantApplyFormRoute,
  MerchantApplySubmittedRoute: MerchantApplySubmittedRoute,
  RiderApplyFormRoute: RiderApplyFormRoute,
  RiderApplySubmittedRoute: RiderApplySubmittedRoute,
  CustomerOrdersIndexRoute: CustomerOrdersIndexRoute,
  MerchantApplyIndexRoute: MerchantApplyIndexRoute,
  MerchantOrdersIndexRoute: MerchantOrdersIndexRoute,
  MerchantProductsIndexRoute: MerchantProductsIndexRoute,
  MerchantProfileIndexRoute: MerchantProfileIndexRoute,
  MerchantSettingsIndexRoute: MerchantSettingsIndexRoute,
  MerchantStaffIndexRoute: MerchantStaffIndexRoute,
  RiderApplyIndexRoute: RiderApplyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
